# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8509941958b27f5ad06148a993e2fc37621bd5dc7d0476e97363821708161d72be1f65480729b7fe482efbe563dbf4612f796af69c512ff46175ee0ba2ce974e

test:
  secret_key_base: dc2692d62ba90a2d324dc0b108baa1f1e266353280cba8190efdd3230ee3e91c83967c9de2fa12f5d125a8e253baac7d38a0cd6889f854905aadd760e8ff13e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
